### ISSUE TITLE
Improve contrast control interface

### ISSUE THREAD

**Issue by MarkRivers** [mrkraimer/PY_NTNDA_Viewer#12]
Rather than pixel levels (0,255), there should be 2 sliders, one for the lower level and one for the upper level.

There should also be a text field for each slider to directly type the value.

The sliders will interact so that the lower level is never more than the upper level.

The sliders should re-draw the current image so that even if no new images are arriving one can adjust the display.

**Comment by mrkraimer** [comment]
I will start on this next.

**Comment by mrkraimer** [comment]
I just pushed support for PixelLevelControl.

**Comment by MarkRivers** [comment]
I tested that on Linux and it works.  Some suggestions:

- If the lower slider is increased to value of the upper slider-1 then it should increment both the upper and slower slider, keeping a difference of 1.  Same if the upper slider is decreased to lower slider+1 it should move the lower slider.
- It would be nice to have these controls on the main screen and not have to open another screen.

**Comment by mrkraimer** [comment]
On 2/13/20 8:45 AM, Mark Rivers wrote:
>
> I tested that on Linux and it works. Some suggestions:
>
>   * If the lower slider is increased to value of the upper slider-1
>     then it should increment both the upper and slower slider, keeping
>     a difference of 1. Same if the upper slider is decreased to lower
>     slider+1 it should move the lower slider.
>
OK
>
>   * It would be nice to have these controls on the main screen and not
>     have to open another screen.
>
Good idea.
I am also going to implement the snap feature of EPICS_NTNDA_Viewer.
There will separate sliders for the dynamic image and for the snap image.

**Comment by mrkraimer** [comment]
On 2/13/20 8:45 AM, Mark Rivers wrote:
>
> I tested that on Linux and it works. Some suggestions:
>
>   * If the lower slider is increased to value of the upper slider-1
>     then it should increment both the upper and slower slider, keeping
>     a difference of 1. Same if the upper slider is decreased to lower
>     slider+1 it should move the lower slider.
>

I still need to do this
>
>   * It would be nice to have these controls on the main screen and not
>     have to open another screen.
>

Done.
I also added snap.
I still want to improve look and do more testing.

**Comment by mrkraimer** [comment]
I pushed changes to improve user interface.
I still want to do more testing but should almost be ready for users.

**Comment by mrkraimer** [comment]
I pushed more changes:

1) when dtype changes set location of tick marks
2) don't start if channelName is empty
3) add env variable **EPICS_NTNDA_VIEWER_CHANNELNAME**

**Comment by mrkraimer** [comment]
I have pushed more changes including changes to address issue 13.
Note that changeImage buttons do not work.

**Comment by mrkraimer** [comment]
This is now implemented
