### ISSUE TITLE
Add zoom control

### ISSUE THREAD

**Issue by MarkRivers** [mrkraimer/PY_NTNDA_Viewer#13]
Add control to zoom the image within the current window.  This will not make the window larger, but will control how much of the image is visible.

If this is easy with the Qt widget it should be done.  Not worth writing a lot of code for.

**Comment by mrkraimer** [comment]
I am making an attempt to do this.
I do not think it is possible with RawImageWidget.
I will try with pyplotimage.
But now yet working.

**Comment by mrkraimer** [comment]
I made another attempt.
Not sure how this satisfies request.

**Comment by mrkraimer** [comment]
I have another idea but will take a couple of days to implement
The idea is that when a snapImage button is pressed a new window will come up.
It will allow the user to enter a region start and size (x and y) just like the simDetector screen allows.
It will then create an image that has the selected region but expanded.
It will again use RawImageWidget to display the new image.

I can not see anyway for the user ti use the mouse to select the region so the user will have to manually enter the values.

**Comment by mrkraimer** [comment]
I have pushed an implementation of zoom
Still needs more testing

**Comment by mrkraimer** [comment]
zoom is now implemented
