### ISSUE TITLE
Images are rotated 90 degrees

### ISSUE THREAD

**Issue by MarkRivers** [mrkraimer/PY_NTNDA_Viewer#2]
I set simDetector in Peaks mode with a single elliptical peak that is larger in Y than in X.

![PeaksMode](https://user-images.githubusercontent.com/6115534/71787159-0a46a780-2fda-11ea-8742-29fdce4ce297.png)

This is what the display looks like with the ImageJ viewer.

![ImageJ](https://user-images.githubusercontent.com/6115534/71787164-234f5880-2fda-11ea-99af-d24724fad4cd.png)

However, in the Python display it looks like this:

![Python](https://user-images.githubusercontent.com/6115534/71787183-55f95100-2fda-11ea-92f1-213fc95257eb.png)

**Comment by mrkraimer** [comment]
This appears to be fixed by latest version.
