### ISSUE TITLE
color mode problem

### ISSUE THREAD

**Issue by mrkraimer** [mrkraimer/PY_NTNDA_Viewer#8]
color mode RGB1 works, but RGB2 and RGB3 do not work.

**Comment by mrkraimer** [comment]
On 2020.01.13 changes were pushed that should fix this problem.

It was quite an odyssey to get to the current version.
I started out thinking that the only efficient way to implement RGB2 and RGB3 was via numpy.
But after several failed attempts I tried not using numpy.
But then the performance was really bad. Less than 4 frames per second.

I then spent more time looking at numpy and came up with the current version.
It uses only numpy methods  to manipulate the image array.
It is efficient!!

I still want to do more testing before closing this issue.

**Comment by MarkRivers** [comment]
This seems to be fixed in my testing.
